# Generated by Django 3.1.4 on 2020-12-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='userId',
            new_name='user',
        ),
    ]
