# Generated by Django 3.1.4 on 2020-12-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20201222_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='owner',
            new_name='user',
        ),
    ]
